### ISSUE TITLE
I still have an actions feed in my own profile view

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#153]
![screen shot 2015-09-01 at 7 33 34 pm](https://cloud.githubusercontent.com/assets/3653904/9619665/5f8c8b8e-50e0-11e5-992d-4ebdba5d448e.png)

**Comment by joshuapowell** [comment]
It's important to understand how this works.

We do not expose role information publicly for security reasons. If we did, an admin account could be targeted, we want to avoid this.

I have put a fix in place, but if the number of closures is not 0 the Actions list is still going to show up for non-admin users.

Now, the thinking goes like this. SINCE only an admin can close a Report, this number should always, always, always be zero for non-admins. IF you see any other "Actions" for non-admins prior to launch it's because of old data.

BUT if you see it list "0 Actions" for non-admin users ... let me know because we have a bug.

**Comment by joshuapowell** [comment]
<img width="1552" alt="screen shot 2015-09-02 at 11 48 42 am" src="https://cloud.githubusercontent.com/assets/569351/9636276/94e6d284-5168-11e5-9c17-bee6a52110d1.png">

<img width="1552" alt="screen shot 2015-09-02 at 11 48 59 am" src="https://cloud.githubusercontent.com/assets/569351/9636289/9d18cbd8-5168-11e5-899a-bbfd9e95692b.png">
