### ISSUE TITLE
Submit Report Form Map doesn't recenter after using the geocoder more than once

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#172]

**Comment by joshuapowell** [comment]
This seems to be entirely related to the same bug that was cuasing the issues in #174.

The resolution to #174 was to downgrade the Angular Leaflet Directive to v0.8.5 from v0.8.8. We built the development server against the previous version (0.8.5) and only accidentally upgraded to the new version on the server (0.8.8). Because of a renaming of Leaflet Directive attributes (i.e., from `center` to `lf-center`) it causing the scope to set initially (because of a variable setup, weird) but would break after being updated (still don't understand why it worked once, but not twice).

**Comment by joshuapowell** [comment]
@rdawes1 Back in your court for testing on the development server.

**Comment by rdawes1** [comment]
This is fixed and works great!
