### ISSUE TITLE
Issue with forgot password

### ISSUE THREAD

**Issue by rdawes1** [WaterReporter/www.waterreporter.org#175]
If a user signs in with the wrong password, our prompt fires but routs them back to explore page.  Should probably just do the notification and keep them at the sign in page.

**Comment by joshuapowell** [comment]
I think that you and I will need to setup a call to discuss and recreate this together. I'm a bit lost at how you get to the places you say you do.

**Comment by joshuapowell** [comment]
After deployment I tested this on the server. It turns out that in the SecurityInterceptor--factory.js file we added an "automatic logout" feature. Meaning that if the user got a 403 for any reason, it would kill there cookies and return them to the home page. We realize that this is less than ideal, we are unsure why we made this decision, and we resolved the issue.
